-- Row Level Security for all eleven candidate tables.
--
-- Generated by a loop over a fixed table list rather than 44 hand-written
-- policies. That is the safer choice here, not the lazier one: every table gets
-- provably identical rules, and there is no opportunity for one table to be
-- given a subtly wrong predicate by copy-paste. The block at the bottom then
-- verifies the result and aborts the migration if anything is missing.
--
-- Design notes:
--   * TO authenticated only. No policy exists for anon, so a signed-out request
--     matches nothing and returns zero rows.
--   * (select auth.uid()) rather than bare auth.uid(): the subselect is
--     evaluated once as an InitPlan instead of once per row.
--   * UPDATE carries USING *and* WITH CHECK. Without WITH CHECK a user could
--     rewrite user_id and hand a row to someone else — or claim one.
--   * Ownership is always the table's own user_id column, which references
--     auth.users directly. No joins, nothing to get wrong.

do $$
declare
  target_table text;
  candidate_tables text[] := array[
    'profiles',
    'job_preferences',
    'automation_settings',
    'work_authorizations',
    'work_experiences',
    'education_entries',
    'skills',
    'certifications',
    'projects',
    'languages',
    'verified_answers'
  ];
begin
  foreach target_table in array candidate_tables loop
    execute format('alter table public.%I enable row level security', target_table);

    -- Belt and braces: also applies the policies to the table owner, so a
    -- future owner-context query cannot silently bypass RLS.
    execute format('alter table public.%I force row level security', target_table);

    -- anon gets nothing at all; authenticated gets only the four DML verbs.
    --
    -- authenticated must be revoked FIRST, not just granted to. Supabase's
    -- default privileges hand it ALL on new public tables, which includes
    -- TRUNCATE — and TRUNCATE is not subject to row security. Left in place, any
    -- signed-in user could empty a table for every other user, RLS
    -- notwithstanding. REFERENCES and TRIGGER come along the same way and are
    -- equally unnecessary from a client.
    execute format('revoke all on public.%I from anon', target_table);
    execute format('revoke all on public.%I from public', target_table);
    execute format('revoke all on public.%I from authenticated', target_table);
    execute format('revoke all on public.%I from service_role', target_table);
    execute format('grant select, insert, update, delete on public.%I to authenticated', target_table);

    execute format($p$
      create policy %I on public.%I
        for select to authenticated
        using ((select auth.uid()) = user_id)
    $p$, target_table || '_select_own', target_table);

    execute format($p$
      create policy %I on public.%I
        for insert to authenticated
        with check ((select auth.uid()) = user_id)
    $p$, target_table || '_insert_own', target_table);

    execute format($p$
      create policy %I on public.%I
        for update to authenticated
        using ((select auth.uid()) = user_id)
        with check ((select auth.uid()) = user_id)
    $p$, target_table || '_update_own', target_table);

    execute format($p$
      create policy %I on public.%I
        for delete to authenticated
        using ((select auth.uid()) = user_id)
    $p$, target_table || '_delete_own', target_table);
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- Self-verification. The migration fails rather than leaving a table exposed.
-- ---------------------------------------------------------------------------
do $$
declare
  expected_tables text[] := array[
    'profiles', 'job_preferences', 'automation_settings', 'work_authorizations',
    'work_experiences', 'education_entries', 'skills', 'certifications',
    'projects', 'languages', 'verified_answers'
  ];
  offending text;
begin
  -- Every listed table must exist with RLS enabled and forced.
  select string_agg(t, ', ')
    into offending
  from unnest(expected_tables) as t
  where not exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = t and c.relrowsecurity and c.relforcerowsecurity
  );
  if offending is not null then
    raise exception 'RLS not enabled/forced on: %', offending;
  end if;

  -- Exactly four policies each.
  select string_agg(t || ' (' || cnt || ')', ', ')
    into offending
  from (
    select t, (select count(*) from pg_policies p where p.schemaname = 'public' and p.tablename = t) as cnt
    from unnest(expected_tables) as t
  ) s
  where cnt <> 4;
  if offending is not null then
    raise exception 'Expected 4 policies per table, found: %', offending;
  end if;

  -- No policy may be granted to anon or PUBLIC.
  select string_agg(tablename || '.' || policyname, ', ')
    into offending
  from pg_policies
  where schemaname = 'public'
    and tablename = any(expected_tables)
    and (roles::text[] && array['anon', 'public']);
  if offending is not null then
    raise exception 'Policies reachable by anon/public: %', offending;
  end if;

  -- anon must hold no privilege on any of these tables.
  select string_agg(table_name || '.' || privilege_type, ', ')
    into offending
  from information_schema.role_table_grants
  where table_schema = 'public'
    and table_name = any(expected_tables)
    and grantee = 'anon';
  if offending is not null then
    raise exception 'anon still holds grants: %', offending;
  end if;

  -- authenticated must hold the four DML verbs and nothing else. TRUNCATE in
  -- particular ignores row security, so its presence would be a data-loss hole
  -- across every user's rows.
  select string_agg(table_name || '.' || privilege_type, ', ')
    into offending
  from information_schema.role_table_grants
  where table_schema = 'public'
    and table_name = any(expected_tables)
    and grantee = 'authenticated'
    and privilege_type not in ('SELECT', 'INSERT', 'UPDATE', 'DELETE');
  if offending is not null then
    raise exception 'authenticated holds privileges beyond DML: %', offending;
  end if;

  -- service_role must hold nothing either. No application code carries that
  -- key, and it bypasses RLS, so a standing grant would be privilege kept
  -- "just in case" on the most sensitive tables in the product.
  select string_agg(table_name || '.' || privilege_type, ', ')
    into offending
  from information_schema.role_table_grants
  where table_schema = 'public'
    and table_name = any(expected_tables)
    and grantee = 'service_role';
  if offending is not null then
    raise exception 'service_role still holds table grants: %', offending;
  end if;

  raise notice 'RLS verified: 11 tables, 4 policies each; anon and service_role have no access.';
end;
$$;

-- ---------------------------------------------------------------------------
-- Function privilege verification
-- ---------------------------------------------------------------------------
-- Tables were audited from the start; functions are the easier thing to miss,
-- because PostgreSQL grants EXECUTE to PUBLIC by default and Supabase's default
-- privileges add anon on top. This asserts the least-privilege result and fails
-- the migration if any later change re-opens it.
do $$
declare
  -- Only these may be executable by authenticated, and only because CHECK
  -- constraints evaluate them as the inserting user.
  check_helpers text[] := array['text_array_matches', 'text_array_no_blanks'];
  offending text;
begin
  -- Nothing in public may be executable by PUBLIC.
  select string_agg(p.proname, ', ')
    into offending
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and has_function_privilege('public', p.oid, 'EXECUTE');
  if offending is not null then
    raise exception 'PUBLIC can still execute: %', offending;
  end if;

  -- anon must not be able to execute anything.
  select string_agg(p.proname, ', ')
    into offending
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and has_function_privilege('anon', p.oid, 'EXECUTE');
  if offending is not null then
    raise exception 'anon can still execute: %', offending;
  end if;

  -- Nor service_role, for the same reason it holds no table grants.
  select string_agg(p.proname, ', ')
    into offending
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and has_function_privilege('service_role', p.oid, 'EXECUTE');
  if offending is not null then
    raise exception 'service_role can still execute: %', offending;
  end if;

  -- authenticated may execute the CHECK helpers and nothing else. In
  -- particular not the trigger function, which does not need it.
  select string_agg(p.proname, ', ')
    into offending
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and has_function_privilege('authenticated', p.oid, 'EXECUTE')
    and not (p.proname = any(check_helpers));
  if offending is not null then
    raise exception 'authenticated can execute more than the CHECK helpers: %', offending;
  end if;

  -- ...and must still be able to execute those two, or every INSERT touching a
  -- validated array column would fail.
  select string_agg(h, ', ')
    into offending
  from unnest(check_helpers) as h
  where not exists (
    select 1 from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = h
      and has_function_privilege('authenticated', p.oid, 'EXECUTE')
  );
  if offending is not null then
    raise exception 'authenticated lost EXECUTE on required CHECK helper(s): %', offending;
  end if;

  -- No SECURITY DEFINER, and every function keeps an explicit empty
  -- search_path. PostgreSQL stores `SET search_path = ''` in proconfig as the
  -- quoted form search_path="" — both spellings are accepted here so the
  -- assertion tests the setting rather than the way it was written.
  select string_agg(p.proname, ', ')
    into offending
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and (
      p.prosecdef
      or p.proconfig is null
      or not (p.proconfig && array['search_path=""', 'search_path='])
    );
  if offending is not null then
    raise exception 'Function is SECURITY DEFINER or lacks search_path="": %', offending;
  end if;

  raise notice 'Function privileges verified: PUBLIC and anon have none; authenticated has only the CHECK helpers.';
end;
$$;
